# Generated by Django 4.1.3 on 2022-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_undopost_undo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='undopost',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
